module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'chore', 'docs', 'test', 'perf', 'style', 'ci', 'revert'],
    ],
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'domain',
        'application',
        'adapters',
        'platform',
        'mobile',
        'api',
        'docs',
        'adr',
        'spec',
        'solutions',
        'skills',
        'agents',
        'hooks',
        'deps',
        'tooling',
        'deploy',
        'ci',
        'release',
        'view-library',
        'auth-integration',
        'discover-music-v1',
        'discover-music-v2',
        'discover-music-v3',
        'view-result-detail',
        'acquire-track',
        'discovery-foundation-v1',
        'discovery-identity-v1',
        'resilience-v1',
        'related-tracks',
        'acquire-soundcloud',
        'musicbrainz-enrichment',
        'go-api',
        'overseer',
        'acquisition',
        'admin',
        'app',
        'auth',
        'catalog',
        'discovery',
        'feedback',
        'observe',
        'playback',
        'shared',
        'detail',
        'discover',
        'library',
        'settings',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    'body-max-line-length': [1, 'always', 100],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
  },
};
