module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'chore', 'docs', 'test', 'perf', 'style', 'ci', 'revert'],
    ],
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        // Layer scopes (backend hexagonal split)
        'domain',
        'application',
        'adapters',
        'platform',
        // Cross-cutting
        'mobile',
        'api',
        'docs',
        'adr',
        'spec',
        'solutions',
        'claude-md',
        'rules',
        'skills',
        'agents',
        'hooks',
        'deps',
        'tooling',
        'ci',
        'release',
        // Feature scopes — extend as features get created via /feature-spec
        // (the feature-spec skill appends new scopes here automatically)
        'view-library',
        'auth-integration',
        'discover-music-v1',
        'discover-music-v2',
        'discover-music-v3',
        'view-result-detail',
        'acquire-track',
        'discovery-foundation-v1',
        'discovery-identity-v1',
        'resilience-v1',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    'body-max-line-length': [1, 'always', 100],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
  },
};
