package domain

const (
	ExtraArtworkPath     = "artwork_path"
	ExtraConsensusStatus = "consensus_status"
	ExtraAlbum           = "album"
	ExtraDuration        = "duration"
	ExtraGenre           = "genre"
	ExtraExplicit        = "explicit"
	ExtraFeaturedArtists = "featured_artists"
	ExtraPreviewURL      = "preview_url"
	ExtraListeners       = "listeners"
	ExtraPlaycount       = "playcount"
	ExtraPlaybackCount   = "playback_count"
	ExtraTrackNumber     = "track_number"
	ExtraDiscNumber      = "disc_number"
	ExtraCopyright       = "copyright"
	ExtraUPC             = "upc"
	ExtraMBID            = "mbid"
	ExtraDisambiguation  = "disambiguation"
	ExtraOwnedTrackID    = "owned_track_id"
	ExtraTrackPosition   = "track_position"
	ExtraRecordType      = "record_type"
	ExtraResolutionTier  = "resolution_tier"
)
